### PR TITLE
docs(components): Grid component

### PR DESCRIPTION
**Pull request by bdfranck**
## Motivations

This PR adds a `<Grid>` proposal.

### CODE REVIEW

**Comment by chris-at-jobber** [comment]
@bdfranck This looks like a great first crack! For the purposes of alignment with @ChristyCampos 's work on a future layout vision, I'd suggest we rename this to `Layout` as your initial component will probably serve as the first building block of a larger system - @GetJobber/mcweb might have more thoughts on technical implementation. One thing we'll probably need to consider for IE11 support is a graceful degradation/progressive enhancement approach, possibly using flexbox?

**Comment by eddysims** [comment]
@chris-at-jobber @bdfranck I like the idea of this. Tagging @seanhealy and @JeffMarvin for discussion as well.

Are we open to using CSS grid and grid template areas for the implementation? I have an idea for this that I **think** would make the usage nice, the problem would be IE support.

My very rough thought of usage would be something like this:

```ts
const template = `
head head head
sidebar body body
footer footer footer
` 

<Grid template={template} spacing={"small" | "base" | "large"}>
    <GridItem area={head}>
        ...head content
    </GridItem>
    <GridItem area={sidebar}>
        ...sidebar content
    </GridItem>
    <GridItem area={body}>
        ...body content
    </GridItem>
    <GridItem area={footer}>
        ...footer content
    </GridItem>
</Grid>
```

With the option to change the `template` prop to an array of breakpoints with new templates. It would be a change in thinking from flexbox, but would allow for some more flexible layouts.


https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-areas
https://css-tricks.com/snippets/css/complete-guide-grid/
https://caniuse.com/css-grid

**Comment by chris-at-jobber** [comment]
@eddysims I think we need to start looking at `Grid` implementations that can fall back to a simpler flex solution - whether that's a single column, or just some less sophisticated reflow, this feels to me like a great use case for "start with functional, enhance along with the user's system capabilities"

**Comment by chris-at-jobber** [comment]
@bdfranck Given the state of the drawer work I think we can close this one off and re-open if it's needed again

**Pull request closed without merging**
