### PR TITLE
feat(design): Add the loadingCheck icon

### PR DESCRIPTION
**Pull request by JordanMacHattie**
## Motivations

We need a new icon to for some message center updates. Initially to indicate dedicated phone number registration is in progress.

### Added

- Added a new icon called: loadingCheck
image

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by MattDekinder** [comment]
This LGTM but I'll leave approval for @GetJobber/atlantis

**Comment by fagnanm** [comment]
@JordanMacHattie just chatting with Jill about a potential tweak to this icon. Shouldn't take too long to make the adjustments.

**Comment by JordanMacHattie** [comment]
> @JordanMacHattie just chatting with Jill about a potential tweak to this icon. Shouldn't take too long to make the adjustments.

Sounds good, let me know (or I can reach out to Jill later today) when that's ready!

**Comment by fagnanm** [comment]
@JordanMacHattie she has the new icon now, so should be able to provide it

**Review by taylorvnoj — APPROVED** [review]
Approved on behalf of Matt and Atlantis! I'll merge it for you @JordanMacHattie - feel free to install `@jobber/design` where you need the icon 🚀

**Pull request merged**
