### PR TITLE
feat(hooks): create breakpoints hook

### PR DESCRIPTION
**Pull request by darryltec**
## Motivations

Make it easier for devs to use the same breakpoints as the CSS counterpart. Instead of having to add a listener to `window.resize` and matching it up with a random number, devs can just use this hook to check if they should render their component on our supported breakpoints.

### Added

- `useBreakpoints` hook that gives you the sizes that we support
- `mockViewportWidth` to easily test it on your own codebase

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by MichaelParadis** [comment]
I love this idea just going to say shipit without even looking at the code 🤣

**Comment by MichaelParadis** [comment]
@rodrigoeidelvein I may be able to take a look tomorrow. I am super busy with my team's sprint work. Don't hold this up for my review :)

**Comment by darryltec** [comment]
@rodrigoeidelvein realized that the smallAndBelow should actually be extraSmallOnly. Though it didn't clear your review but would be good to get a sanity check on that one

**Comment by rodrigoeidelvein** [comment]
> @rodrigoeidelvein realized that the smallAndBelow should actually be extraSmallOnly. Though it didn't clear your review but would be good to get a sanity check on that one

@darryltec I can see the point of renaming it to `extraSmallOnly`, but should we? Because the CSS variable is called `--small-screens-and-below`, maybe we should keep it similar because we're using those values as reference too.

**Comment by darryltec** [comment]
@rodrigoeidelvein I was okay with it because `only` doesn't really exist on the CSS breakpoint and it's a JS specific thing since it doesn't cascade like CSS does.

Also, might need to update that one on design as well since it is also semantically wrong haha

**Comment by rodrigoeidelvein** [comment]
@darryltec Okay, it makes sense to me. But let's not update the CSS variable now, I don't know if someone is already using those CSS variables, but seems risky.

LGTM

**Comment by darryltec** [comment]
@rodrigoeidelvein agreed!

**Pull request merged**
