### PR TITLE
fix(components): DataList UI updates

### PR DESCRIPTION
**Pull request by darryltec**
## Motivations

There are a few design tweaks we need to do to make the DataList UI more harmonious and polished

### Added

- 

### Changed

- Ensure the height of each item is at a minimum of 56px so we reduce the amount of varying heights
- Remove focus on the clickable row to let the parent handle the styling of it
- Ensure bulk action doesn't change the height of the header
- More spacious loading glimmers
- Larger glimmers on wide screens
- Ensure tags doesn't wrap when there's more than 1 word inside a tag
- Ensure focus doesn't get clipped on filters and batch actiions

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Review by chris-at-jobber — COMMENTED** [review]
In terms of the changes you made, looks great! Two outstanding issues:

- Checkbox alignment (I know this is a weird one to implement, but basically we want it to _look_ like the Checkbox component where the checkmark indicator is aligned to the first line of the "label")

image

- Weird one on the quick actions hover menu. The padding on the left only is larger than top/right/bottom:
image

If those fixes need to happen in a separate PR let me know and I'll design approve this, the changes explicitly addressed in your PR description have been resolved. If you want to do the fixes here, I'll hold off.

**Comment by darryltec** [comment]
the actions one can be easily fixed. The checkbox one is a bit complex

**Comment by darryltec** [comment]
@chris-at-jobber thanks brah. the actions one, i'll fix that. that should be easy. the checkbox needs a bit of thought since it isn't really tied to any element as the elements within data list could be anything

**Review by chris-at-jobber — APPROVED** [review]
Looks _great_ to me

**Pull request merged**
