### PR TITLE
Job 61137 fix(components) Emphasis Svg not included in build

### PR DESCRIPTION
**Pull request by MichaelParadis**
### Added

- 

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- Inline the Emphasis SVG so it is included in components release builds

### Security

- 

## Testing

- Install new dependencies.
- Run a npm build.
- Navigate to `dist/typography-<numbers>.js
- Observe there is an inline SVG background image for the emphasis class

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by chris-at-jobber** [comment]
@MichaelParadis this change _could_ actually point to master as the brushstroke highlight is already in production. I don't think it's required as the "time to production" shouldn't change drastically one way or the other, but just an FYI

**Comment by chris-at-jobber** [comment]
Design-wise looks good (no change in how the highlight is presented) - I'll tag the engineers to look at the build-related things 😄

**Comment by MichaelParadis** [comment]
@chris-at-jobber I can cherry-pick the commit once it is merged to get it into master as well.

**Review by taylorvnoj — APPROVED** [review]
LGTM!

**Pull request merged**
