### PR TITLE
feat(design): Add opacity tokens to Atlantis web

### PR DESCRIPTION
**Pull request by taylorvnoj**
## Motivations

To help setup a single source of truth for Design Tokens between jobber-mobile and web, opacity tokens now live in Atlantis

### Added

 
Added `opacity.css` to be included in the design build

## Testing

Run `npm run build -w @jobber/design` in Atlantis to see the opacity tokens land in `packages/design/foundation.js`

pre-release: `npm i @jobber/components@4.7.1-tay.2+92c06a7b @jobber/design@0.32.1-tay.5+92c06a7b`

You can go to `jobber-mobile` and delete the opacity tokens from `mobile-foundation.ts`.  Test on the `Button` in Storybook to see opacity remains and is being pulled from `@jobber/design` & test in simulator

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by taylorvnoj** [comment]
I decided not to create a `stories.mdx` file for `opacity`, much like we don't have one for `shadows` and `timing` but I am open to changing that!

**Comment by taylorvnoj** [comment]
Also a thought moving forward in the future: Atlantis uses opacity values in components like `Divider`, `Select`, `Icon` but they are all different values than the tokens we had in mobile.  Is it worth adding more opacity tokens down the line and streamlining this a bit more?

**Review by rodrigoeidelvein — CHANGES_REQUESTED** [review]
Just a nitpick on the new function

**Review by rodrigoeidelvein — APPROVED** [review]
LGTM!

**Pull request merged**
