### PR TITLE
chore: Audit Atlantis packages

### PR DESCRIPTION
**Pull request by eddysims**
## Motivations

Atlantis packages are getting pretty far out of date. This PR will do an audit of vulnerabilities for `most` of the Atlantis npm packages.

There are some packages that need to be audited outside of this PR as they have a much much larger impact.

**Notes**

Updating the `typed-css-modules` caused a change to the way that css types are made. This causes changes in every `.css.d.ts`.

As part of this I have also ignored the `.css.d.ts` files in the `eslintignore` file as these are auto generated and we shouldn't care about linting them.

### Added

- 

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

- pull down branch
- run all the `npm` scripts
- see they all work

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by chris-at-jobber** [comment]
For posterity: I have done some "random" QA of Atlantis and have not noticed any glaring issues with any of the functionality or components.

**Comment by joelwarrington-jobber** [comment]
need any more 👀  on this?

**Comment by eddysims** [comment]
@joelwarrington-jobber If you have time that would be great

**Comment by adambobadam** [comment]
LGTM!

**Review by adambobadam — APPROVED** [review]

**Pull request merged**
