### PR TITLE
docs(components): Add ThumbnailList Story

### PR DESCRIPTION
**Pull request by taylorvnoj**
## Motivations

Documentation between web and mobile now need to be unified. This adds an overview Docs page & Mobile story for `ThumbnailList`

### Added

`ThumbnailList` refers to `Gallery` on the `Docs` page since it is essentially the same component - just not named the same thing at the moment

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by rodrigoeidelvein** [comment]
The images are not fully rendering and some are flickering... It's happening on jobber-mobile too 😨

**Comment by taylorvnoj** [comment]
@rodrigoeidelvein yeah I've briefly talked to Darryl about that and was wondering if I should just ship the docs and then add a ticket to figure that out afterward.  It might be related to FormatFile as well...

**Comment by taylorvnoj** [comment]
Update: I just created a ticket in the backlog to investigate the flickering/lack of loading, etc.

**Review by rodrigoeidelvein — APPROVED** [review]
LGTM!

We should add EDM to this page, then the flickering would be a feature and not a bug

**Pull request merged**
