### PR TITLE
fix(components): Style fixes for Toast

### PR DESCRIPTION
**Pull request by eddysims**
## Motivations

The `Toast` component needed some styling adjustments. 

## Changes

Some css styling on the `Toast`

### Added

- 

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- Padding, Color, Z-index of the Toast

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by eddysims** [comment]
@rebecca-li want to take a look at this as well

**Comment by rebecca-li** [comment]
- Close icon should be Grey Blue Dark #424E56

other than that looks good

**Comment by eddysims** [comment]
> * Close icon should be Grey Blue Dark #424E56
> 
> other than that looks good

@rebecca-li I realized now that the close icon is using a `[Button](https://atlantis.getjobber.com/components/button)` component that looks like this

```
<Button
  icon="remove"
  type="tertiary"
  variation="cancel"
/>
```

Thoughts on what we should do here?

**Comment by rebecca-li** [comment]
As long as we're being consistent with all our dismiss icons, it should be fine. For our Atlantis modal, what is that using? https://atlantis.frend.space/components/modal

**Comment by eddysims** [comment]
> As long as we're being consistent with all our dismiss icons, it should be fine. For our Atlantis modal, what is that using? https://atlantis.frend.space/components/modal

Modal is using just an `Icon` component, not the `Button`.

**Pull request merged**
