### PR TITLE
feat(components): Implement Chip Group component

### PR DESCRIPTION
**Pull request by joelwarrington-jobber**
## Motivations

Follow on PR to https://github.com/GetJobber/atlantis/pull/629

### Added

- 

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by hosseintalebi** [comment]
@joelwarrington-jobber is it possible to use the [compound component](https://kentcdodds.com/blog/compound-components-with-react-hooks) patterns a syntax like this:
```ts
<ChipGroup>
   <Chip />
   <Chip />
</ChipGroup>
```
This will result in a more declarative API for the component.

**Comment by joelwarrington-jobber** [comment]
> @joelwarrington-jobber is it possible to use the [compound component](https://kentcdodds.com/blog/compound-components-with-react-hooks) patterns a syntax like this:
> 
> ```ts
> <ChipGroup>
>    <Chip />
>    <Chip />
> </ChipGroup>
> ```
> 
> This will result in a more declarative API for the component.

Good point, I can investigate that. Primarily the purpose of this component would be to control the value of child-chips, so I'm wondering if I can make it so child `<Chip />` components don't set the the `selected` prop to true/false

the only purpose of putting chips would be to set the label/icons/avatars, atleast that's what I'm thinking right now

**Comment by hosseintalebi** [comment]
@joelwarrington-jobber In compound components you provide a state from the parent (`ChipGroup`) to the children (`Chip`) through the [context API](https://reactjs.org/docs/context.html). That way, the state of the selected chip is still managed on the `ChipGroup` but can be accessed from each child (`Chip`) through context.

**Comment by chris-at-jobber** [comment]
Closing as @darryltec is picking this up in a new PR

**Pull request closed without merging**
