### PR TITLE
build: Prerelease packages on Pull Requests

### PR DESCRIPTION
**Pull request by eddysims**
## Motivations

There has been a few questions come up about how to make sure that your changes in Atlantis will work when brought into your next project.

This PR will create a pre-release for every push to a branch. Meaning that contributors will be able to test their code changes in their project before their work gets merged into master.

### Added

- 

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by eddysims** [comment]
This is a comment added from node.

**Comment by eddysims** [comment]
This is a comment added from node.

**Comment by eddysims** [comment]
This is a comment from Circle CI.

**Comment by eddysims** [comment]
This is a comment from Circle CI.

## Packages

@jobber/components@2.46.8

@jobber/design@0.17.0

@jobber/docz-tools@1.7.11

@jobber/eslint-config@0.8.0

@jobber/formatters@0.2.0

@jobber/generators@0.5.0

@jobber/hooks@1.5.3

@jobber/stylelint-config@0.3.0

**Comment by eddysims** [comment]
:package: hello

**Comment by eddysims** [comment]
:package:  Your prerelease packages are ready

### Prereleased packages

`@jobber/components@2.46.9-pull.15+c6fd2c5`

`@jobber/design@0.17.0`

`@jobber/docz-tools@1.7.12-pull.15+c6fd2c5`

`@jobber/eslint-config@0.8.0`

`@jobber/formatters@0.2.0`

`@jobber/generators@0.5.0`

`@jobber/hooks@1.5.3`

`@jobber/stylelint-config@0.3.0`

**Comment by chris-at-jobber** [comment]
@eddysims do you want to keep this PR around or can we close this as "learnings" based on your architecture talk?

**Comment by chris-at-jobber** [comment]
Not closing so this can be referenced in a more earnest attempt to get this working.

**Pull request closed without merging**
