### PR TITLE
fix(components): make autocomplete work in input groups

### PR DESCRIPTION
**Pull request by JeffMarvin**
## Motivations

This allows Autocomplete components to be used inside of InputGroup components and work properly with the layout.

### Added

- Autocomplete can now be used inside of InputGroups.

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

1. View the test page: http://localhost:3333/components/input-group-test or https://app.netlify.com/sites/jobber-atlantis/deploys/5f32d73b9699e40008338fbe/components/input-group-test
2. Observe that the Autocomplete displays correctly in the two examples.
3. Feel free to test out any edge cases in the playground code.

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by eddysims** [comment]
@JeffMarvin what is the `.mdx` in here?

**Comment by JeffMarvin** [comment]
> @JeffMarvin what is the `.mdx` in here?

For testing only, I think. See the testing notes in the PR description.We can remove it before we merge.

**Comment by eddysims** [comment]
@JeffMarvin code looks good, my only thought is to add an autocomplete to the `InputGroup` docs.

**Comment by JeffMarvin** [comment]
@eddysims Done, and cleaned up the non-shippable cruft, so unblocking the PR.

**Pull request merged**
