### PR TITLE
fix(components): BREAKING CHANGE: redefine ButtonProps

### PR DESCRIPTION
**Pull request by jklotz1**
### Added

- 

### Changed

- rename what ButtonProps are so that `variation` and `type` can be passed in when using `Modal` components on `primaryAction`, `secondaryAction` and `tertiaryAction`
- Other places that are using `ButtonProps` will now be restricted to properly following all `Button` restrictions. For example Cancel Buttons can not be primary.

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by seanhealy** [comment]
@jklotz1 I think we've hit an odd type issue with the build on this one. We can look at it together in the morning if that works for you?

**Comment by JeffMarvin** [comment]
@seanhealy Looks straightforward, in terms of the code. 
A couple of questions:
- should the PR title mark a major change?
- There is a `TODO` list at the start of the description. Is that still valid?

**Comment by JeffMarvin** [comment]
I still have a question about the TODO at the start of the description -- seems to indicate that test can/should be written for this.

**Comment by seanhealy** [comment]
Note to let @tyler-santos know when this lands so he can clean out a `@ts-ignore` that resulted because of it.

**Comment by tyler-santos** [comment]
> Looks good. @tyler-santos heads up that this is going into Atlantis master now. Contact a Frend if you want help bringing it into Jobber.

Thanks Jeff!

**Pull request merged**
