### PR TITLE
chore(components): prep card for retheme

### PR DESCRIPTION
**Pull request by darryltec**
## Motivations

Same as modal, retheme cards. This allows us to split off the styling of the modal when `jobber-retheme` class names exists on the body

### Added

- styling that only exists for `jobber-retheme`

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

Add the `jobber-retheme` class name on the body within the preview iframe

image

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by chris-at-jobber** [comment]
Are we going to need to do the same "space preservation" for small-screens that Matt [added back in here](https://github.com/GetJobber/sg-1/pull/1388#pullrequestreview-1784522643)?

**Comment by darryltec** [comment]
@chris-at-jobber Oh, yup!!

**Comment by chris-at-jobber** [comment]
Good call preserving these clickable ones at least for the time being
image

**Comment by chris-at-jobber** [comment]
Not a blocker - I don't _think_ anyone has actually applied this treatment but if they have, they're Going to Have A Bad Time™
image

**Review by chris-at-jobber — CHANGES_REQUESTED** [review]
All the changes that have been made look good, just need that mobile responsive padding

**Review by chris-at-jobber — APPROVED** [review]
Approved (pending specs)

**Pull request merged**
