### PR TITLE
feat(components): Expose all sizing tokens in web Content

### PR DESCRIPTION
**Pull request by taylorvnoj**
## Motivations

Let's support all sizing tokens on Content, for flexibility when using the component

### Added

Exposed `minuscule`, `smallest`, `smaller`, `larger`, `largest` and `extravagant` as props on Content `spacing` prop

## Testing

Make sure all options on `spacing` prop changes the vertical spacing between children in Content story.

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by taylorvnoj** [comment]
@chris-at-jobber my only question is - we also have `Paddings.css` in the Content folder but it seemingly is doing nothing? It's not being called anywhere. Unless you have additional context, I'm thinking of just deleting that paddings file

**Comment by chris-at-jobber** [comment]
@taylorvnoj that's an old @darryltec file from the looks of it - there _are_ some non-obvious internal bits to Content so there's a chance it _could_ be doing something, somewhere. I'd leave it for now unless we're 100% confident it doesn't do anything? My first guess was it was at least intended to allow for Content's padding to be controlled (the same way we do on the mobile component), but I don't think we ever exposed that ability 🤔

**Review by chris-at-jobber — APPROVED** [review]
This looks and works great! Approved, pending what we want to do with that possibly useless `Padding` file

**Comment by chris-at-jobber** [comment]
Also, semantically I'd argue this PR is a `feat()` PR as it does introduce new functionality.

**Comment by darryltec** [comment]
Doesn't seem to be used anywhere. If you delete it and it still bootstraps, you should be good

**Pull request merged**
