### PR TITLE
docs(hooks): MDX File Documentation for UseCollectionQuery and useIsMounted Hooks [32207]

### PR DESCRIPTION
**Pull request by jlapstra**
## Motivations

To document the use of the two hooks

### Added

- MDX files for useIsMounted and useCollectionQuery.

## Testing

http://localhost.test:3333/hooks/use-collection-query
1. 4 items in the list
2. Fetch More loads 4 more
3. Refresh updates to the first 4 items in step 1. (THIS WILL NOT WORK. UseCollectionQuery is working correctly, however there seems to be some weirdness with useQuery and this particular endpoint. Still to investigate!)

http://localhost.test:3333/hooks/use-is-mounted
1. When this page is opened there will be an alert
2. Unmount component will trigger another alert
3. Unmounting can be done by clicking the button or heading to a different page.

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by jlapstra** [comment]
@tyler-santos I'd love your thoughts on making an mdxUtils folder and separating out the stuff in that file to multiple files.

**Comment by tyler-santos** [comment]
👀

**Comment by tyler-santos** [comment]
I have only 3 little things: 

1. There are a bunch of unused imports that should get cleaned up.
2. Lets swap the list icon logo from a star to something else because it looks like its waiting for something to load that never does.
3. Lets put a comment explaining why we don't use query types in the actual code example (playgrounds are not compatible with query types), it was confusing to me to see it used in the proper shown example but then omitted in the code that actually runs. 
4. Perhaps lets indicate someway in the initial example that subscription is optional? and perhaps put that in the title beside subscription in the props section. 
ie
```
Subscription (optional)
```

**Comment by jlapstra** [comment]
@tyler-santos Ready for round 2!

**Comment by tyler-santos** [comment]
👀

**Comment by tyler-santos** [comment]
LGTM

**Review by tyler-santos — APPROVED** [review]
LGTM

**Pull request merged**
