### PR TITLE
fix(components): update combobox list to use overflow: auto rather than scroll

### PR DESCRIPTION
**Pull request by gregorijobber**
## Motivations

We're seeing some strange behaviors of the Combobox list trying to use scrollbars even we don't need them (as per image below)

image

### Added

- 

### Changed

- Update Combobox List styling to use `overflow: auto` rather than `overflow: scroll`

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Review by scotttjob — COMMENTED** [review]
From a coding perspective this fine to me. I ran the code and confirmed the scrollbars are hidden so all good there.

I haven't actually approved it though, as I'd like our designer to weigh in just to make sure there wasn't a design decision for the scrollbars to be present before we take them out (in which case we can probably move this option to a prop).

**Comment by gregorijobber** [comment]
> From a coding perspective this fine to me. I ran the code and confirmed the scrollbars are hidden so all good there.
> 
> I haven't actually approved it though, as I'd like our designer to weigh in just to make sure there wasn't a design decision for the scrollbars to be present before we take them out (in which case we can probably move this option to a prop).

As this change will not hide the scrollbars if they're needed (keep in mind that I've added `auto` rather than `hidden`) I don't think we need to worry about this @scotttjob but yes let's wait for a design review! Check [this slack 🧵](https://getjobber.slack.com/archives/C03BJHV3PMG/p1702415065654259?thread_ts=1702414572.886209&cid=C03BJHV3PMG) too!

**Comment by gregorijobber** [comment]
@chris-at-jobber we'll wait for your 👀 on this one! Thanks in advance!

**Comment by gregorijobber** [comment]
Good catch @fagnanm! Fixed!

**Review by scotttjob — APPROVED** [review]
LGTM! Saw the design approval, and it looks/works well. Thanks for the contribution!

**Pull request merged**
