### PR TITLE
feat(components-native): Update Button learning variation style

### PR DESCRIPTION
**Pull request by jdeichert**
## Motivations

Updating our mobile Button `learning` variation color tokens for the retheme.

### Changed

- Updated mobile Button color tokens from `information` to `interactive` for the `learning` variation
- Updated tests

## Testing

Check out the mobile Button in Storybook and apply the `learning` variation type. All types should now use the interactive color.

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by taylorvnoj** [comment]
Code looks good but I'm hoping for design thoughts.  `cancel` and `learning` `tertiary` buttons are now exactly the same and I'm wondering if this could lead to any confusion moving forward?
cc @fagnanm @chris-at-jobber 

Screenshot 2024-03-11 at 1 11 09 PM
Screenshot 2024-03-11 at 1 11 18 PM

**Comment by chris-at-jobber** [comment]
@taylorvnoj not a concern here. We need to get rid of cancel and replace with subtle eventually, and keeping learning/subtle separate from a props perspective keeps us able to iterate on learning buttons independently of subtle

**Comment by taylorvnoj** [comment]
Perfect, thanks @chris-at-jobber - that makes sense to me!

**Review by taylorvnoj — APPROVED** [review]
LGTM

**Pull request merged**
