### PR TITLE
chore(components): Reupdate react-router-dom and types

### PR DESCRIPTION
**Pull request by adambobadam**
This PR reverts the revert made [here](https://github.com/GetJobber/atlantis/pull/1101) of the original PR [here](https://github.com/GetJobber/atlantis/pull/1089).  

The reason it was initially reverted was because when we brought Atlantis components into JO to test it broke there - see context here:
- https://getjobber.slack.com/archives/C03BKPST4KC/p1677790942293559
- https://getjobber.slack.com/archives/C03BKPST4KC/p1677636103833679

### CODE REVIEW

**Review by timoteialbu — APPROVED** [review]

**Review by kingstonfung — APPROVED** [review]

**Review by darryltec — CHANGES_REQUESTED** [review]
@adambobadam homes! point this baby in this branch https://github.com/GetJobber/atlantis/pull/1111 instead of master

**Comment by adambobadam** [comment]
@darryltec done!

**Comment by darryltec** [comment]
looks like package-lock on root ain't updated here homes. Can you rerun npm install?

**Review by darryltec — APPROVED** [review]
We good homes!

**Pull request merged**
