### PR TITLE
feat(design): Add Marketing Icon

### PR DESCRIPTION
**Pull request by miqdadamirali**
### Added

Added a new Icon for marketing to be used for Marketing Email for SPs.

### Changed

image

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Review by chris-at-jobber — CHANGES_REQUESTED** [review]
Based on the comments in [this Figma](https://www.figma.com/file/3aXNxoNQgFVyPLxcLgtV0G?node-id=4852:27286&mode=design#572336402) this icon is not finished being designed and so shouldn't be added to Atlantis yet. Let's either put a `blocked` status on this PR, or close it and put up a new one once ready.

**Comment by MichaelParadis** [comment]
@chris-at-jobber we have updated the PR with the new approved icon

**Review by chris-at-jobber — CHANGES_REQUESTED** [review]
@rebecca-li can you adjust the "nub" so that it's centered in the bullhorn? Currently it's sitting on the lower end.

image

**Comment by rebecca-li** [comment]
> @rebecca-li can you adjust the "nub" so that it's centered in the bullhorn? Currently it's sitting on the lower end.
> 
> image

Thanks for catching that! Made some tweaks:
base
large
small

**Comment by chris-at-jobber** [comment]
Looks much better! @miqdadamirali @rebecca-li if you can add the updated icon I'll give this another review

**Comment by MichaelParadis** [comment]
@rebecca-li @chris-at-jobber I updated the icon with the new ones Rebecca posted

**Pull request merged**
