### PR TITLE
refactor(components): new sendMessage Icon

### PR DESCRIPTION
**Pull request by kkimble006**
### Added

- 

### Changed

Updated Icon to have new sendMessage Icon 
Screen Shot 2020-07-07 at 12 36 32 PM

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by kkimble006** [comment]
@chris-at-jobber is this approved (state still looks like its review requested so just want to confirm) and good to be merged?

**Comment by seanhealy** [comment]
Did you use the import script to do this? Did it have to be moved as we thought it would?

**Comment by kkimble006** [comment]
> Did you use the import script to do this? Did it have to be moved as we thought it would?

@seanhealy  Yeah, I ended up manually moving it
(after generating the file with the import script)

**Comment by chris-at-jobber** [comment]
Yep this is approved

**Pull request merged**
