### PR TITLE
docs: add IconButton docs

### PR DESCRIPTION
**Pull request by darryltec**
## Motivations

What's that? Oh yeah, docs migration.

### Added

- IconButton docs baby!

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Review by rodrigoeidelvein — COMMENTED** [review]
It looks good, the only thing that I found is that I get an error when I try to set a badge for the IconButton.

Currently, on Atlantis Mobile, we can't change the props in the props table, but now we have the option and it's not working... maybe it's an easy fix?

**Comment by darryltec** [comment]
it is not. it needs a component

**Comment by rodrigoeidelvein** [comment]
@darryltec maybe we can think of making this prop only a string instead of a component as a future improvement for this

**Review by rodrigoeidelvein — APPROVED** [review]
LGTM!

**Pull request merged**
