### PR TITLE
fix(components): Ensure DataList sorting gets cleared in a predictable manner

### PR DESCRIPTION
**Pull request by darryltec**
## Motivations

- If you have Name and Home world as sortable
- Home world is sorted to be descending
- Clicking Name clears all of the sorting instead of setting Name as sorted

### Added

- Ensure we only clear sorting when you've clicked the header that's on descending

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by chris-at-jobber** [comment]
@darryltec the description sounds good - is there a way to test this in Storybook? None of the sortable headers actually sort for me on this branch or prod (which is probably how we got into this state in the first place 😅)

**Comment by chris-at-jobber** [comment]
Is it possible for the sort order to remain consistent when you switch headers? What I see right now is

- I have a column sorted ascending 
- click another sortable header
- new header is sorted descending

- I have a column sorted descending 
- click another sortable header
- new header is sorted ascending

(video incoming)

**Comment by darryltec** [comment]
@chris-at-jobber totally! right now they always reset to ascending. 

_So technically it does that, but only for ascending_ 😆

**Comment by chris-at-jobber** [comment]
> right now they always reset to ascending

That's not what I'm seeing - I'm seeing it flip to the opposite order of your currently sorted column

**Comment by chris-at-jobber** [comment]
https://us02web.zoom.us/clips/share/lFIAGEZSXXXq_ieaOCO3FLNZWecCUAE1WDDF0aNMpUPc9qkq3tnkZY9oLpAzqm5mID4laixASr9SfKZevrjlo_mZEA.xj8bTSuMgCsM6gp5

**Comment by darryltec** [comment]
@chris-at-jobber Oh that is 100% a bug. did not do what i was expecting either haha

**Comment by darryltec** [comment]
@chris-at-jobber aaaaand fixed! Good catch

**Review by chris-at-jobber — COMMENTED** [review]
Design approved ✅

**Review by rodrigoeidelvein — APPROVED** [review]
LGTM! 

Thanks for fixing the icon alignment too!

**Pull request merged**
