### PR TITLE
docs: add grammar guide and move product vocab to content section

### PR DESCRIPTION
**Pull request by chris-at-jobber**
## Motivations

Added a grammar guide to house a recently decided-upon convention for pre-requisite instructions in Atlantis.

This is a new kind of content guide, so I made a section for Content that can grow as we add more content guidelines to our design system.

VERY OPEN to thoughts on...
- the name of the guide
- the name of the section "Explaining prerequisites"

**TODO:** I tried changing the order of the sidenav groups to move Content above Changelog but eslint got made at me about something unrelated to my change so... I left it alone

## Changes

New content section! New guide!

### Added

-Grammar and structure guide

### Changed

- Product vocab guide -> content section

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by rebecca-li** [comment]
New category looks good. Wondering if this guideline would apply to other situations too -- not just for explaining prerequisites. I think it is good practice to lead with verb in other situations too. (verb / do 'X') to (outcome).

**Comment by chris-at-jobber** [comment]
@rebecca-li good call!

**Comment by chris-at-jobber** [comment]
@rebecca-li ready for another look! I talked to Eric from B&C and added some references to the overall Jobber V&T, as well as some more specific product examples.

**Comment by rebecca-li** [comment]
LGTM!

**Review by rebecca-li — APPROVED** [review]
The new V&T updates are looking great!

**Pull request merged**
