### PR TITLE
feat(components-native): Add stepped variation of progress bar for mobile

### PR DESCRIPTION
**Pull request by jjwlee94**
## Motivations
- There are projects coming up that anticipate to use the stepped progress bar in mobile; might as well do it at once 🙂

### Added
- Stepped variation of the progress bar.
  - Animation was not added due to the note in `ProgressBarInner` that there's issues with Android.
### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by chris-at-jobber** [comment]
Just a question on it not working with `inProgress` - is there a reason this variation shouldn't support that? It seems like a viable use case.

**Comment by jjwlee94** [comment]
@chris-at-jobber Hm good question, I thought there wouldn't be a viable use case as I saw the stepped variation as an indicator of progress in a current flow (through signup, through a form, etc.) rather than as an indicator of status (visits/appointments). I can include the functionality for the stepped variation though, to keep the options flexible!

**Review by chris-at-jobber — COMMENTED** [review]
Design approved, thanks @jjwlee94 !

**Review by scotttjob — APPROVED** [review]
LGTM.

I pulled the code down, ran things locally. The code in ProgressBarStepped could probably be tidied up a bit, but it's not enough of a feedback comment to hold up this great work.

No changes to the top-level API, so I'm not anticipating any issues merging with existing instances of ProgressBar.

**Comment by chris-at-jobber** [comment]
@jjwlee94 congrats on making the top 30 all-time [commits contributors](https://github.com/GetJobber/atlantis/graphs/contributors) to Atlantis! 🎉 A few more contributions and you'll be in the top 20 easily 😄
image

**Pull request merged**
