### PR TITLE
refactor: Use Tertiary Button on dismiss Modal

### PR DESCRIPTION
**Pull request by xen0m29**
Task Undertaken: #382 

## Changes

- Use Tertiary Button on dismiss Modal

### Changed

- Modal Component

- Modal Test Snapshot

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by eddysims** [comment]
@xen0m29 There are some strange `package-lock` changes in here. They seem unnecessary. Can you take a look at these.

**Comment by eddysims** [comment]
@chris-at-jobber can you take a look at this? Using the `Button` changes the look of the `Modal`. Something that may not have been considered. Is this okay?

**Comment by chris-at-jobber** [comment]
@eddysims what I would propose we do outside of the scope of this PR is create a `DismissButton` component that powers Modal, Toast, etc, only accepts the `cross` icon, has a repeatable behaviour defined for handling `onDismiss` and has a transparent background. Is it possible for this PR to add CSS to `Modal` that makes the current "close" button transparent?

**Comment by eddysims** [comment]
>  Is it possible for this PR to add CSS to Modal that makes the current "close" button transparent?

Not without some hacky css that changes the `Button` component. If we were to do that, I don't know if there would be gains of the current `Icon` implementation.

**Comment by eddysims** [comment]
Closing in favour of https://github.com/GetJobber/atlantis/pull/395

Thank you @xen0m29 for your contributions, we really appreciate it!

**Pull request closed without merging**
