### PR TITLE
feat(components): Add showPicker on click for InputTime element [JOB-83556]

### PR DESCRIPTION
**Pull request by rahulshial**
## Motivations

To emulate the same functionality as `InputDate` where clicking into (focussing) in the date field brings up the `date picker`, this PR adds the same functionality for the `InputTime`.

### Changed

- Add `onClick` method to the FormField Types
- Add `onClick` to `InputTime` component to `showPicker` on click
- Update css to remove the `picker` icon

## Testing

- [ ] To test this feature, run `npm start` to start `storybook`, navigate to `InputTime` from SearchBox, navigate to `Event`
image
- [ ] Clicking in the input time element should show the `time picker`

https://github.com/GetJobber/atlantis/assets/68708089/33836985-5c8b-48df-b17d-fa15943bc26f

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by chris-at-jobber** [comment]
> clicking into (focussing) in the date field

In testing, I can see that _clicking_ the input triggers the time picker, but _focusing_ via keyboard does not. Is that intended?

In InputDate, the calendar icon can be tabbed to and activated by keyboard:

image

**Comment by rahulshial** [comment]
> > clicking into (focussing) in the date field
> 
> In testing, I can see that _clicking_ the input triggers the time picker, but _focusing_ via keyboard does not. Is that intended?
> 
> In InputDate, the calendar icon can be tabbed to and activated by keyboard:
> 
> image

@chris-at-jobber - Focussing via the keyboard in the InputDate also does not trigger the picker. Clicking the InputDate and the Calendar Icon triggers the DatePicker. We want the TimePicker to trigger onClick, and we also want to incorporate a `reset` (clearable input) icon for the time via this [sub-task](https://jobber.atlassian.net/jira/software/c/projects/JOB/boards/274?quickFilter=948&selectedIssue=JOB-83557). The Date can be selected and cleared, but the time uses `input` tag which does not allow selecting the entire time element and clear it out. Hence the `time icon` was removed. 

LMK your thoughts..

**Comment by chris-at-jobber** [comment]
@rahulshial I think we're on the same page here! I mainly wanted to clarify the intended behaviour, as the PR says _"Clicking in (focussing) the input time element should show the time picker"_, but right now only `click` triggers the picker, while pressing `space` is the keyboard trigger for the picker. 

One note about Safari is that Safari does not show a picker for `click` or `space` on time inputs, so if our intended approach is "follow the browser's heuristics for whether and when to show a time picker" then the current experience is working as intended. If the goal is to create a standard behaviour across browsers than we might need to do something custom, but I'm assuming we're starting off by following the browsers' lead?

**Comment by rahulshial** [comment]
> @rahulshial I think we're on the same page here! I mainly wanted to clarify the intended behaviour, as the PR says _"Clicking in (focussing) the input time element should show the time picker"_, but right now only `click` triggers the picker, while pressing `space` is the keyboard trigger for the picker.
> 
> One note about Safari is that Safari does not show a picker for `click` or `space` on time inputs, so if our intended approach is "follow the browser's heuristics for whether and when to show a time picker" then the current experience is working as intended. If the goal is to create a standard behaviour across browsers than we might need to do something custom, but I'm assuming we're starting off by following the browsers' lead?

@chris-at-jobber - You're right that the `space` does not trigger the picker, but the click does.

Regarding the approach, yes we would want to follow the browser's heuristics to keep this input consistent with the current functionality.

**Review by taylorvnoj — APPROVED** [review]
LGTM - tested in Storybook & JO. Let me know when you'd like me to merge this for you

**Comment by rahulshial** [comment]
> LGTM - tested in Storybook & JO. Let me know when you'd like me to merge this for you

I guess if it is approved, we can merge it? but not released to JO as yet - does that work?

**Review by classtronaut — COMMENTED** [review]
Reviewed for Work Setup, LGTM

**Comment by taylorvnoj** [comment]
We're going to hold off on merging this PR for now - after discussing more in Office Hours, this change affects existing typing behaviour in Chrome/Edge for this input. Team Atlantis will have to discuss this further.

**Comment by chris-at-jobber** [comment]
I've just chatted with @jlelford and the intention was not that users could _only_ enter time via the browser's timepicker. We'll need to better define what the expected interaction here is before moving ahead with this PR for now!

**Comment by rahulshial** [comment]
> I've just chatted with @jlelford and the intention was not that users could _only_ enter time via the browser's timepicker. We'll need to better define what the expected interaction here is before moving ahead with this PR for now!

I agree - what we have here does not work as was expected. I think some of the conversation slipped thru the cracks, and I thought that this was the intended behaviour. So entirely my bad.. :(

**Comment by rahulshial** [comment]
This PR is not needed anymore

**Pull request closed without merging**
