### PR TITLE
docs: code sandbox not rendering on browser refresh

### PR DESCRIPTION
**Pull request by darryltec**
## Motivations

it was due to the storybook API not being there on refresh

### Added

- guard storybook API before destructuring

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

On atlantis.getjobber.com, go to any code tab
Reload the browser
It fails

Try it on this branch
It don't fail no mo

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Review by rodrigoeidelvein — COMMENTED** [review]
It's not failing anymore, but it's not opening in the right tab, for example: https://fix-code-sandbox-not-renderi.atlantis.pages.dev/?path=/code/components-actions-button-web--basic

You can see in the URL that I sent the code tab, but it opens the Canvas

**Comment by darryltec** [comment]
@rodrigoeidelvein because we forced it to. storybook quirk https://github.com/GetJobber/atlantis/blob/e0259358eefede57b5d95684159f399bd4948e51/docs/components/Button/Web.stories.tsx#L13

**Comment by rodrigoeidelvein** [comment]
> @rodrigoeidelvein because we forced it to. storybook quirk
> 
> https://github.com/GetJobber/atlantis/blob/e0259358eefede57b5d95684159f399bd4948e51/docs/components/Button/Web.stories.tsx#L13

Hmm, makes sense, but do we want it? Probably a discussion for another time

**Review by rodrigoeidelvein — APPROVED** [review]
LGTM! I tested with different tabs and components and it works well!

**Pull request merged**
