### PR TITLE
docs: Copy changelog to storybook

### PR DESCRIPTION
**Pull request by darryltec**
### Added

- Stories for changelog

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by taylorvnoj** [comment]
I just have two quick questions:

1. Can we move where the Change Log section is in the sidebar? I wonder if it should go after packages to not break up the flow of Design, Content, etc. And should it be Change Log with a space, or one word Changelog.
2. Under the Contents section on the right, looking at Components Change log for example, the list is super long. Is there a way to organize that by months/years?

Happy to approve otherwise!

**Comment by darryltec** [comment]
> Can we move where the Change Log section is in the sidebar? I wonder if it should go after packages to not break up the flow of Design, Content, etc.

Totes can!

>  And should it be Change Log with a space, or one word Changelog.

These guys says 1 word

image

and they package is for changelog (we don't use them) so I kinda believe them haha

> Under the Contents section on the right, looking at Components Change log for example, the list is super long. Is there a way to organize that by months/years?

Quick answer no since this is just a doc that a bot updates. You'd actually see this (or the MD file) in every github repo 😆

**Comment by taylorvnoj** [comment]
Thanks @darryltec! 

Cool, I believe those guys too 😆  In that case, can we then go in the `CHANGELOG.md` files for each and make that heading one word also?

Screenshot 2023-03-10 at 10 35 35 AM

**Comment by darryltec** [comment]
yah gots it!

**Review by taylorvnoj — APPROVED** [review]
Wooo thank you! 🚀

**Pull request merged**
