### PR TITLE
docs(components): Tweak some verbiage and order of the Popover docs

### PR DESCRIPTION
**Pull request by chris-at-jobber**
## Motivations

Gave the Popover docs a quick re-read after release, just some cleanups and design clarifications.

Also pulled in the border variable I'd introduced alongside the build of this component, which is available now!

### Added

- add a11y notes
- add related components

### Changed

- use title-case when referencing component names
- flesh out design use cases
- use `color-border` design variable

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by chris-at-jobber** [comment]
@chriscarline mind giving this a look-over next week? 🙏

**Comment by chriscarline** [comment]
This may be overkill but I'm wondering if some visuals might help in understanding the usage guidelines — similar to some of the other pages in Atlantis?

**Comment by chriscarline** [comment]
Is there a specific reason for the 3 line limit on content?

**Comment by chris-at-jobber** [comment]
> Is there a specific reason for the 3 line limit on content?

I think that was a "rule of thumb" or suggested best practice that originally lived on Tooltip. Generally speaking it's more of a suggestion to keep things concise, not something actually enforced... do you think that could be made clearer?

**Comment by chris-at-jobber** [comment]
@chriscarline some changes! added a visual example of an informational Popover, and some notes around why we don't have a componentized "functional" popover yet, also clarified the "three lines" thing a bit.

**Review by chriscarline — APPROVED** [review]

**Pull request merged**
