### PR TITLE
docs(components): Improve Combobox Custom Search Example

### PR DESCRIPTION
**Pull request by ZakaryH**
## Motivations

per some feedback on the initial `onSearch` PR, it would be preferable to have more realistic code as an example for how to implement a custom search with the `onSearch` prop talking to an api to fetch results based on the query

## Changes

swapped out the scuffed code to use Apollo stuff to talk to a Richard and Mortimer character API

make a lil util file with the necessary code because if you have it in the webstory bad things happen, plus it's tidier this way

### Added

- 

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- 

### Security

- 

## Testing

just play around with it! see that you have some options loaded initially

search for some characters not available in the initial set of data, see that it fetches them

undo the search term, get your initial options back!

I will say it's very hard to see the loading state now. I'm not sure this setup is actually ever setting loading to be `true` long enough to be perceptible...

it is definitely toggling the value, but it's difficult to see the loading state at all

image

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Review by darryltec — CHANGES_REQUESTED** [review]
Looks good! Would need to inject the files to the code sandbox for it to work there like this 

https://github.com/GetJobber/atlantis/blob/03135427c5c110b2922e22328fa0469dcede77a1/docs/components/Chips/Web.stories.tsx#L123-L126

and then import it

https://github.com/GetJobber/atlantis/blob/03135427c5c110b2922e22328fa0469dcede77a1/docs/components/Chips/Web.stories.tsx#L120-L122

**Comment by darryltec** [comment]
as for testing the loading state, can test it with throttling your internet through dev tools

**Comment by ZakaryH** [comment]
updated and imported, it is working on the code tab now

for my own knowledge, since I copied this pattern from the DataList - I'm assuming we have no need to do this `extraImport` stuff there since the code tab is hidden for DataList?

**Comment by darryltec** [comment]
> for my own knowledge, since I copied this pattern from the DataList - I'm assuming we have no need to do this extraImport stuff there since the code tab is hidden for DataList?

yup. for now

**Review by darryltec — APPROVED** [review]
🚢

**Pull request merged**
