### PR TITLE
feat(components): Add new “money” icons

### PR DESCRIPTION
**Pull request by BenA-jobber**
## Motivations
Adding the `money` icon so that we can display it for the Jobber Money feature

### Added
added `money` icon and updated storybook. `money` icon is placed under `transaction`
Screenshot 2023-03-29 at 11 55 30

## Testing
- [ ] `npm run start`
- [ ] check that the new `money` icon exists

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by BenA-jobber** [comment]
> @BenA-jobber it looks correct but a bit small

hmm. i think it should be the same size as all the other icons, which is set to 1024 (pixels?). @taylorvnoj can you verify this please :)

**Comment by darryltec** [comment]
I guess in relation to the wallet icon, it looks a tad bit small. Might want to double check how it got exported from figma. If that's correct, then check how it got imported in icomoon. the white-space around the icons is normally the culprit as to what makes it smaller than the other even though it's the same size

**Comment by darryltec** [comment]
Oh, ha! It is actually built smaller so @MadsCogen1 might wanna adjust it from the grid to accommodate the circle or leave it as is

image

image

**Comment by MadsCogen1** [comment]
Oh I see, I think this should be fine @BenA-jobber

**Review by taylorvnoj — APPROVED** [review]
Tested in `jobber-mobile` and everything looks good! Thanks Ben! 🚀

**Pull request merged**
