### PR TITLE
feat(design): add new icons to atlantis -- (Minor) Feature Release

### PR DESCRIPTION
**Pull request by jlapstra**
## Motivations

- The filter Icon is needed for Communigrade work, and while including the icon we have included two others that were also added by the design team!
- Followed these directions: https://jobber.atlassian.net/wiki/spaces/DES/pages/1658585445/Technical+Guide+Adding+an+icon+to+Jobber+s+design+system#Adding-to-Atlantis

## Changes

- Three new icons have been added to atlantis

### Added

- PaperClip, Image and Filter icons

## Testing

Make sure that you can go to the Icons page in Atlantis and see three new icons: Paperclip, Image and Filter.

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Review by chris-at-jobber — APPROVED** [review]
Thanks for getting these brought in @jlapstra !

**Comment by jlapstra** [comment]
@chris-at-jobber Hello! I am wondering if I need merge permissions? The process is the same as JO, correct?

Screen Shot 2022-02-22 at 3 01 13 PM

**Review by joelzwarrington — APPROVED** [review]
LGTM

**Comment by chris-at-jobber** [comment]
@jlapstra Ah! I need to get you added into the McFriends Github group (thanks @joelzwarrington 😄 )

**Pull request merged**
