### PR TITLE
fix(hooks): Fix useCollectionQuery error state when fetching more

### PR DESCRIPTION
**Pull request by rodrigoeidelvein**
## Motivations

Fixing the error state of `useCollectionQuery`. Before, it was just doing a `console.error` when it failed on `fetchMore`. I added a state for the error and updated it when necessary.

I also added a test for this case.

### Added

- 

### Changed

- 

### Deprecated

- 

### Removed

- 

### Fixed

- Fixed the error state of `useCollectionQuery` when it fails on `fetchMore`

### Security

- 

## Testing

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by darryltec** [comment]
We should reset that error state when it actually goes through. Right now it keeps it in there even if it successfully does the query the second time.

**Comment by rodrigoeidelvein** [comment]
@darryltec I added a reset before the methods where they can be updated, that it makes sense or should we reset on a successful call?

**Comment by darryltec** [comment]
@rodrigoeidelvein yeah since the error isn't valid at that point, yeah?

**Comment by rodrigoeidelvein** [comment]
@darryltec exactly, it basically cleans up before making the request because we don't know what's going to happen next

**Comment by darryltec** [comment]
Ok, one more ask, let's write a test on the clearing the error part

**Comment by rodrigoeidelvein** [comment]
@darryltec I added one more expect to that same test to make sure it's cleared after a successful fetch

**Review by darryltec — APPROVED** [review]
:shipit:

**Pull request merged**
