### PR TITLE
fix(components): apply correct cursors on labels within FormField components

### PR DESCRIPTION
**Pull request by joelzwarrington**
## Motivations

Labels within FormFields and some FormField types do not have pleasant cursor types to indicate what type of action would take place.

- [Autocomplete](https://atlantis.getjobber.com/components/autocomplete)
    - label does not have text cursor
- [InputEmail](https://atlantis.getjobber.com/components/input-email)
    - label does not have text cursor
- [InputNumber](https://atlantis.getjobber.com/components/input-number)
    - label does not have text cursor
- [InputPassword](https://atlantis.getjobber.com/components/input-password)
    - label does not have text cursor
- [InputText](https://atlantis.getjobber.com/components/input-text)
    - label does not have text cursor
- [InputTime](https://atlantis.getjobber.com/components/input-time)
    - has no cursor on the entire component
 - [Select](https://atlantis.getjobber.com/components/select)
    - has no cursor on the entire component    
 
### Fixed

- FormFields of type `text`, `password`, `number`, `time`, `textarea`, `email` will all have text cursors even on their labels. This affects:
    - [Autocomplete](https://atlantis.getjobber.com/components/autocomplete)
    - [InputEmail](https://atlantis.getjobber.com/components/input-email)
    - [InputNumber](https://atlantis.getjobber.com/components/input-number)
    - [InputPassword](https://atlantis.getjobber.com/components/input-password)
    - [InputText](https://atlantis.getjobber.com/components/input-text)
    - [InputTime](https://atlantis.getjobber.com/components/input-time)
- FormFields of type `select` will all have text cursors even on their labels. This affects:
    - [Select](https://atlantis.getjobber.com/components/select)
    - Other components which inherit/use [Select](https://atlantis.getjobber.com/components/select), such as [RecurringSelect](https://atlantis.getjobber.com/patterns/recurringselect)

---

[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews).

Random photo of Atlantis

### CODE REVIEW

**Comment by joelzwarrington** [comment]
@darryltec @chris-at-jobber mind reviewing? :pray:

**Comment by chris-at-jobber** [comment]
Hey Joel! We'll try and get some eyes on this next week. First glance it looks good from a design perspective, but I'll want to give it a closer look.

**Review by chris-at-jobber — CHANGES_REQUESTED** [review]
Had a chance to take a look at this! It's looking good with some changes needed to Select, and a question around InputTime.

✅ cursors on all text inputs are behaving as expected

:x: This PR appears to reintroduce an issue with Select that was previously resolved - descenders are being cut off. Appearance differs from browser to browser, as Firefox looks fine but Chrome and Safari are impacted.
### Chrome
image
### Safari
image

I'm wondering if it's related to [this change](https://github.com/GetJobber/atlantis/pull/915/files#diff-2dd45bcb75b2965ffe0b5fceb22778aaea0eb9af7c9912de07dae06ff3f7bafeR59), where it looks like Select-specific styling might be getting removed.

Following up on that, I don't actually see a `cursor: select` in the [spec for the `cursor` property](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor), so I'm wondering if any [Select-related changes](https://github.com/GetJobber/atlantis/pull/915/files#diff-a241f863addccad1f3bf4f9b8f770b0b391031775b7f1dd532972daf63f76e4fR211) should be removed from this PR.

❔ What is the expected cursor change for InputTime? I'm not noticing a difference between this branch and production for Chrome, Firefox, or Safari. (There doesn't necessarily need to be, but the PR description suggests a change is expected)

**Comment by joelzwarrington** [comment]
I don't have the time to look into the issues raised in review above - so am gonna close this PR due to staleness.

**Pull request closed without merging**
